name: Run Supabase Stock Update Job

on:
  schedule:
    # Runs at 4 PM CST (which is 22:00 UTC during standard time, 21:00 UTC during daylight savings)
    - cron: '30 16 * * *' #(4:30 EST)
      timezone: 'America/New_York'
  workflow_dispatch: # allows manual trigger too

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: code/backend
        run: npm install
      
      - name: Run stock update job
        working-directory: code/backend
        run: node build/jobs/supabaseStockUpdate.job.js
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          SB_HOST: ${{ secrets.SB_HOST }}
          SB_PORT: ${{ secrets.SB_PORT }}
          SB_DATABASE: ${{ secrets.SB_DATABASE }}
          SB_USER: ${{ secrets.SB_USER }}
          SB_PASSWORD: ${{ secrets.SB_PASSWORD }}
          USE_SUPABASE: ${{ secrets.USE_SUPABASE }}
          TRADIER_BEARER_TOKEN: ${{ secrets.TRADIER_BEARER_TOKEN }}
